<?php

namespace com\tsphpbots\bots;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-06 at 07:49:38.
 */
class BotManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BotManager
     */
    protected $botManager;

    /**
     *
     * @var Object TS3 server stub
     */
    protected $ts3Server = "TS3 Server STUB";

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->botManager = new BotManager($this->ts3Server);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers com\tsphpbots\bots\BotManager::registerBotClass
     * @todo   Implement testRegisterBotClass().
     */
    public function testRegisterBotClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers com\tsphpbots\bots\BotManager::addBot
     * @todo   Implement testAddBot().
     */
    public function testAddBot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers com\tsphpbots\bots\BotManager::removeBot
     * @todo   Implement testRemoveBot().
     */
    public function testRemoveBot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers com\tsphpbots\bots\BotManager::findBot
     * @todo   Implement testFindBot().
     */
    public function testFindBot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers com\tsphpbots\bots\BotManager::findBotClass
     * @todo   Implement testFindBotClass().
     */
    public function testFindBotClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers com\tsphpbots\bots\BotManager::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers com\tsphpbots\bots\BotManager::loadBots
     * @todo   Implement testLoadBots().
     */
    public function testLoadBots()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers com\tsphpbots\bots\BotManager::createBot
     * @todo   Implement testCreateBot().
     */
    public function testCreateBot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers com\tsphpbots\bots\BotManager::notifyServerEvent
     * @todo   Implement testNotifyServerEvent().
     */
    public function testNotifyServerEvent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers com\tsphpbots\bots\BotManager::notifyBotUpdate
     * @todo   Implement testNotifyBotUpdate().
     */
    public function testNotifyBotUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers com\tsphpbots\bots\BotManager::notifyBotAdd
     * @todo   Implement testNotifyBotAdd().
     */
    public function testNotifyBotAdd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers com\tsphpbots\bots\BotManager::notifyBotDelete
     * @todo   Implement testNotifyBotDelete().
     */
    public function testNotifyBotDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
