<?php

namespace com\tsphpbots\web\controller;
use com\tsphpbots\web\controller\PageLoader;
use com\tsphpbots\utils\TestUtils;
use com\tsphpbots\utils\Log;
use com\tsphpbots\user\Auth;
use com\tsphpbots\user\User;
use com\tsphpbots\db\DB;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-27 at 11:00:04.
 */
class PageLoaderTest extends \PHPUnit_Framework_TestCase {


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {

        $this->assertTrue(DB::connect(), "Database connection failed!");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Provide page parameters for testing.
     * 
     * @return  Page parameters
     */
    public function pageParamsProvider() {
        return [
            [
                ["page" => "Main"],
                ["page" => ""]
            ],
            [
                ["page" => "Login"],
                ["page" => ""]
            ]
        ];
    }

    /**
     * Provide page parameters for testing logged in users.
     * 
     * @return  Page parameters
     */
    public function pageParamsProviderLoggedIn() {
        return [
            [
                ["page" => "Main"],
                ["page" => ""]
            ],
            [
                ["page" => "UserAdmin"],
                ["page" => ""]
            ]
        ];
    }

    /**
     * @covers com\tsphpbots\utils\PageLoader::load
     * @dataProvider  pageParamsProvider
     */
    public function testLoad($GET, $POST) {

        // check the data provider
        $this->assertTrue(($GET !== null), "Internal test error: Invalid data provider detected!");
        $this->assertTrue(($POST !== null), "Internal test error: Invalid data provider detected!");

        // disable HTML output during the tests
        Log::enablePrintEcho(false);
        $pageloader = new PageLoader();
        $res = $pageloader->load($GET, $POST);
        $this->assertTrue($res === true, "Page could not be loaded: " . print_r($GET, true));

        Log::enablePrintEcho(true);
    }

    /**
     * @covers com\tsphpbots\utils\PageLoader::load
     * @dataProvider  pageParamsProviderLoggedIn
     */
    public function testLoggedIn($GET, $POST) {

        // check the data provider
        $this->assertTrue(($GET !== null), "Internal test error: Invalid data provider detected!");
        $this->assertTrue(($POST !== null), "Internal test error: Invalid data provider detected!");

        // create and login user
        $id = TestUtils::createUser("test load page while logged in", "testLoggedIn", "testLoggedIn");
        $this->assertTrue(!is_null($id), "Could not create user!");
        $pw = md5(md5("testLoggedIn") . htmlspecialchars(session_id()));
        $reslogin = Auth::login("testLoggedIn", $pw);
        $this->assertTrue($reslogin == true, "Could not login user!");        
        $this->assertTrue(Auth::isLoggedIn() == true, "Unexpected auth result!");

        // disable HTML output during the tests
        Log::enablePrintEcho(false);
        $pageloader = new PageLoader();
        $res = $pageloader->load($GET, $POST);
        $this->assertTrue($res === true, "Page could not be loaded!");

        Log::enablePrintEcho(true);
        
        // logout and delete the user
        Auth::logout();
        $user = new User($id);
        $user->delete();
    }
}
