<?php

namespace com\tsphpbots\config;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-27 at 16:49:08.
 */
class ConfigTest extends \PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers com\tsphpbots\config\Config::getDB
     */
    public function testGetDB() {

        $this->assertTrue(Config::getDB("host")     != null, "Missing 'host' in database config!");
        $this->assertTrue(Config::getDB("hostPort") != null, "Missing 'hostPort' in database config!");
        $this->assertTrue(Config::getDB("userName") != null, "Missing 'userName' in database config!");
        $this->assertTrue(Config::getDB("password") != null, "Missing 'password' in database config!");
        $this->assertTrue(Config::getDB("dbName")   != null, "Missing 'dbName' in database config!");
    }

    /**
     * @covers com\tsphpbots\config\Config::getTS3ServerQuery
     */
    public function testGetTS3ServerQuery() {

        $this->assertTrue(Config::getTS3ServerQuery("host")         != null, "Missing 'host' in ts3 server query config!");
        $this->assertTrue(Config::getTS3ServerQuery("userName")     != null, "Missing 'userName' in ts3 server query config!");
        $this->assertTrue(Config::getTS3ServerQuery("password")     != null, "Missing 'password' in ts3 server query config!");
        $this->assertTrue(Config::getTS3ServerQuery("hostPort")     != null, "Missing 'hostPort' in ts3 server query config!");
        $this->assertTrue(Config::getTS3ServerQuery("vServerPort")  != null, "Missing 'vServerPort' in ts3 server query config!");
    }

    /**
     * @covers com\tsphpbots\config\Config::getWebInterface
     */
    public function testGetWebInterface() {

        $this->assertTrue(Config::getWebInterface("dirBase")         != null, "Missing 'dirBase' in web interface config!");
        $this->assertTrue(Config::getWebInterface("dirTemplates")    != null, "Missing 'dirTemplates' in web interface config!");
        $this->assertTrue(Config::getWebInterface("dirStyles")       != null, "Missing 'dirStyles' in web interface config!");
        $this->assertTrue(Config::getWebInterface("dirImages")       != null, "Missing 'dirImages' in web interface config!");
        $this->assertTrue(Config::getWebInterface("dirLibs")         != null, "Missing 'dirLibs' in web interface config!");
    }
}
