<?php

namespace com\tsphpbots\utils;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-27 at 10:47:50.
 */
class LogTest extends \PHPUnit_Framework_TestCase {

    protected static $LOGTAG = "LogTest";

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers com\tsphpbots\utils\Log::verbose
     */
    public function testVerbose() {
        Log::verbose(self::$LOGTAG, "This is a verbose message");
    }

    /**
     * @covers com\tsphpbots\utils\Log::debug
     */
    public function testDebug() {
        Log::debug(self::$LOGTAG, "This is a debug message");
    }

    /**
     * @covers com\tsphpbots\utils\Log::info
     */
    public function testInfo() {
        Log::info(self::$LOGTAG, "This is a info message");
    }

    /**
     * @covers com\tsphpbots\utils\Log::error
     */
    public function testError() {
        Log::error(self::$LOGTAG, "This is an error message");
    }

    /**
     * @covers com\tsphpbots\utils\Log::warning
     */
    public function testWarning() {
        Log::warning(self::$LOGTAG, "This is a warning message");
    }

}
